language: php
php:
  - 5.3
  - 5.4
  - 5.5
matrix:
  allow_failures:
    - php: 5.3
    - php: 5.5
install:
  - sudo apt-get update
  - sudo apt-get install php5-dev php-pear
  - composer install
before_script:
  - php-config || true
  - phpenv rehash
  - phpenv version-name
  - bash test/travis-setup.sh
script:
  - bash test/run-pp-tests
  - bash test/run-ext-tests
cache:
  apt: true
  directories:
  - vendor
  - composer.lock
